name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

jobs:
  build:
    name: Continuous Integration
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.1.2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9.12"
      - uses: actions/cache@v2
        with:
          path: |
            ${{ env.pythonLocation }}
            ${{ env.R_LIBS_USER }}/*
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-R-cache
      - name: "Install dependencies"
        run: |
          # Install cython first because we need it for setup.py.
          pip install `cat requirements.txt | grep cython`
          pip install -r requirements.txt
      - name: "Build the project"
        run: "make build"
        env:
          # Our tests may contain a number of stochastic elements. Setting a seed will make sure
          # they're not flaky (but also hide potential issues).
          SEED: "0"
